apiVersion: v1
kind: Service
metadata:
  name: hf-sentiment-service
spec:
  type: ClusterIP # Default type. Exposes the Service on a cluster-internal IP.
  selector:
    app: hf-sentiment
  ports:
    - name: backend
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: frontend
      protocol: TCP
      port: 8000
      targetPort: 8080
